---
# tuxtech-main.yml
# Main playbook for TuxTech infrastructure automations.
# Len Goldenstein
# len@lengoldenstein.com
# https://github.com/lengoldenstein/tuxtech
# Aug 2021

# VMware section BEGIN
- name: 'VMware Configuration'
  # Configure settings for an ESXi host
  hosts: 'all'
  remote_user: 'root'
  # connection: 'local'  # not needed due to role tasks using delegate_to: 'localhost'
  gather_facts: false
  vars:
    # ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    - role: 'tuxtech.vmware.10_configure_esxi'
      # Requirements:
      # - ESXi host must have an IP address, basic network settings and dns entry.
      # - ESXi host must have root password set and matched in tuxtech-configuration.yml
      # Execution:
      # ansible-playbook tuxtech-main.yml --tags vmware_10 --limit mondain.tuxtech.com
      tags:
        - 'vmware_10'
    - role: 'tuxtech.vmware.20_create_vmclients'
      # Create VMware virtual machine guest clients
      # Requirements:
      # - ESXi host must be either in evaluation mode or licensed for vSphere APIs
      # Execution:
      # ansible-playbook tuxtech-main.yml --tags vmware_20 --limit idm,foreman
      tags:
        - 'vmware_20'
        - 'provision'
    - role: 'tuxtech.vmware.99_delete_vmclients'
      # Delete VMware virtual guest clients
      # Requirements:
      # - ESXi host must be either in evaluation mode or licensed for vSphere APIs
      # Execution:
      # ansible-playbook tuxtech-main.yml --tags vmware_99 --limit clients
      tags:
        - 'vmware_99'
        - 'delete'
# VMware section END


# Foreman/Satellite section BEGIN
- name: 'Foreman/Satellite Configuration'
  # Configure settings for an ESXi host
  # Requirements:
  # - ESXi host must have an IP address, basic network settings and dns entry.
  # - ESXi host must have root password set and matched in tuxtech-configuration.yml
  # Execution:
  # ansible-playbook tuxtech-main.yml --tags foreman_20 --limit foreman1.tuxtech.com
  # ansible-playbook tuxtech-main.yml --tags vmware_99 --limit clients
  hosts: 'all'
  remote_user: 'root'
  gather_facts: false
  vars:
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    - role: 'tuxtech.foreman.10_configure_foreman'
      tags:
        - 'foreman_10'
    - role: 'tuxtech.foreman.20_create_hostclients'
      tags:
        - 'foreman_20'
        - 'provision'
    - role: 'tuxtech.foreman.99_delete_hostclients'
      tags:
        - 'foreman_99'
        - 'delete'
# Foreman/Satellite section END


# Operating System section BEGIN
- name: 'OS Configuration'
  # Configure settings for an ESXi host
  # Requirements:
  # - ESXi host must have an IP address, basic network settings and dns entry.
  # - ESXi host must have root password set and matched in tuxtech-configuration.yml
  # Execution:
  # ansible-playbook tuxtech-main.yml --tags foreman_10 --limit foreman1.tuxtech.com
  hosts: 'all'
  # connection: 'local'
  remote_user: 'root'
  gather_facts: false           # host may not exist at this point
  vars:
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    - 'tuxtech.os.10_provision_os'
  tags:
    - 'os_10'
    - 'provision'
# Operating System section END
