---
# tuxtech-main.yml
# Main playbook for TuxTech infrastructure automations.
# Len Goldenstein
# len@lengoldenstein.com
# https://github.com/lengoldenstein/tuxtech
# Aug 2021

# VMware section BEGIN
- name: 'VMware Configuration'
  hosts: 'all'
  remote_user: 'root'
  # connection: 'local'  # not needed due to role tasks using delegate_to: 'localhost'
  gather_facts: false
  vars:
    # ansible_python_interpreter: '{{ ansible_playbook_python }}'  # same as connection: 'local'
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    # Configure settings for an ESXi host
    # - ESXi host must have an IP address, basic network settings and dns entry.
    # - ESXi host must have root password set and matched in tuxtech-configuration.yml
    # ansible-playbook tuxtech-main.yml --tags vmware_10 --limit esxi
    - role: 'tuxtech.vmware.10_configure_esxi'
      tags:
        - 'vmware_10'
    # Create VMware virtual machine guest clients
    # - ESXi host must be either in evaluation mode or licensed for vSphere APIs
    # ansible-playbook tuxtech-main.yml --tags vmware_20 --limit idm,clients
    - role: 'tuxtech.vmware.20_create_vmclients'
      tags:
        - 'vmware_20'
        - 'provision'
    # Delete VMware virtual guest clients
    # - ESXi host must be either in evaluation mode or licensed for vSphere APIs
    # ansible-playbook tuxtech-main.yml --tags vmware_99 --limit clients
    - role: 'tuxtech.vmware.99_delete_vmclients'
      tags:
        - 'vmware_99'
        - 'delete'
# VMware section END


# Foreman/Satellite section BEGIN
- name: 'Foreman/Satellite Configuration'
  hosts: 'all'
  remote_user: 'root'
  gather_facts: false
  vars:
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    # Configure settings for a Foreman/Satellite server
    # - Foreman host must have admin password set and matched in tuxtech-configuration.yml
    # ansible-playbook tuxtech-main.yml --tags foreman_10 --limit foreman1.tuxtech.com
    - role: 'tuxtech.foreman.10_configure_foreman'
      tags:
        - 'foreman_10'
    # Create Foreman host client definitions with MAC address from ESXi
    # - virtual machine must exist in VMware
    # ansible-playbook tuxtech-main.yml --tags foreman_20 --limit idm,clients
    - role: 'tuxtech.foreman.20_create_hostclients'
      tags:
        - 'foreman_20'
        - 'provision'
    # Delete Foreman host clients
    # ansible-playbook tuxtech-main.yml --tags foreman_99 --limit clients
    - role: 'tuxtech.foreman.99_delete_hostclients'
      tags:
        - 'foreman_99'
        - 'delete'
# Foreman/Satellite section END


# Operating System section BEGIN
- name: 'OS Configuration'
  hosts: 'all'
  remote_user: 'root'
  gather_facts: false
  vars:
  vars_files:
    - 'tuxtech-configuration.yml'
  roles:
    # Provision and configure the operating system
    # - inventory host must have matching Foreman/Satellite hostgroup defined
    # ansible-playbook tuxtech-main.yml --tags os_10 --limit idm1.tuxtech.com
    - role: 'tuxtech.os.10_provision_os'
      tags:
        - 'os_10'
        - 'provision'
    # Decommision operating system
    # - inventory host must have matching Foreman/Satellite hostgroup defined
    # ansible-playbook tuxtech-main.yml --tags delete --limit idm1.tuxtech.com
    - role: 'tuxtech.os.99_delete_os'
      tags:
        - 'os_99'
        - 'delete'
# Operating System section END
