---
# Delete host clients from Foreman
- hosts: 'all'
  connection: 'local'
  gather_facts: true
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars_files:
    - 'tuxtech-configuration.yml'
  module_defaults:
    # Can this be external file for cleanliness?
    theforeman.foreman.host:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ foreman_hostname }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
  tasks:

    - name: 'Delete host clients in Foreman'
      theforeman.foreman.host:
        name: '{{ inventory_hostname }}'
        state: 'absent'
