---
# Original script.  Since refactered to role.
- hosts: all
  vars:
  remote_user: root
  module_defaults:
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
  tasks:
  
  - name: 'Update installed software'
    dnf:
      name: '*'
      state: 'latest'

  - name: 'Install required packages'
    dnf:
      name:
        - 'gvim'
        - 'postfix'
        - 'httpd'
        - 'mariadb-server'

  - name: 'System Config: services'
    service:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      enabled: '{{ item.enabled}}'
    loop:
      - { name: 'atd',              state: 'started',   enabled: true }
      - { name: 'auditd',           state: 'started',   enabled: true }
      - { name: 'chronyd',          state: 'started',   enabled: true }
      - { name: 'crond',            state: 'started',   enabled: true }
      - { name: 'dbus',             state: 'started',   enabled: true }
      - { name: 'firewalld',        state: 'stopped',   enabled: false }
      - { name: 'irqbalance',       state: 'started',   enabled: true }
      - { name: 'libstoragemgmt',   state: 'stopped',   enabled: false }
      - { name: 'mcelog',           state: 'stopped',   enabled: false }
      - { name: 'NetworkManager',   state: 'started',   enabled: true }
      - { name: 'polkit',           state: 'started',   enabled: true }
      - { name: 'postfix',          state: 'started',   enabled: true }
      - { name: 'rngd',             state: 'started',   enabled: true }
      - { name: 'rsyslog',          state: 'started',   enabled: true }
      - { name: 'smartd',           state: 'stopped',   enabled: false }
      - { name: 'sshd',             state: 'started',   enabled: true }
      - { name: 'sssd',             state: 'started',   enabled: true }
      - { name: 'tuned',            state: 'started',   enabled: true }
      - { name: 'vmtoolsd',         state: 'started',   enabled: true }

  - name: 'Create UserIDs'
    user:
      name: 'len'
      comment: 'Len Goldenstein'
      groups: 'wheel'

  - name: 'System Config: bash'
    copy: 
      dest: '/etc/profile.d/tuxtech.sh'
      owner: 'root'
      group: 'root'
      mode: '0644'
      content: |
        alias ll='ls -l --color=auto -F'
        alias ls='ls --color=auto -F'
        alias df='df -h'
        alias rm='rm -i'
        alias vi='vim'

  - name: 'System Config: postfix'
    blockinfile:
      path: '/etc/postfix/main.cf'
      state: 'present'
      block: 'relayhost = [mail.tuxtech.com]'
      insertafter: 'EOF'
    notify: 'restart postfix'

#  - name: 'Reboot'
#    reboot:
# 
  

  handlers:
  - name: 'restart postfix'
    service:
      name: 'postfix'
      state: 'restarted'
