---
# Populate Linux hosts in to Foreman with correct host attributes, eg: MAC address
- hosts: 'clients'
  connection: 'local'
  gather_facts: true
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars_files:
    - 'tuxtech-configuration.yml'
  module_defaults:
    # Can this be external file for cleanliness?
    theforeman.foreman.host:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ foreman_hostname }}'
      validate_certs: false
    community.vmware.vmware_guest_info:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest_boot_manager:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
  tasks:

    # Lookup MAC for virtual machine guest
    - name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
      community.vmware.vmware_guest_info:
        name: '{{ inventory_hostname }}'
        datacenter: 'ha-datacenter'
      register: vmguest_info

    - name: 'debug'
      debug:
        var: vmguest_info.instance.hw_eth0.macaddress

    - name: 'Register client to Foreman'
      theforeman.foreman.host:
        name: '{{ inventory_hostname }}'
        hostgroup: 'Tuxtech Provision'
        # interface_attributes:
        #   - type: 'interface'
        #     primary: true
          #   name: 'eth0'
          #   mac: 'EE:BB:01:02:03:04'
          #   provision: true
        mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
        ip: '{{ ipaddr }}'
        organization: 'TuxTech'
        location: 'Default Location'
        state: 'present'


    # Provision
    # Enable Foreman Build mode
    # Power on


    # - name: 'Gather all registered virtual machines'
    #   community.vmware.vmware_vm_info:
    #   register: vminfo
    #   delegate_to: 'localhost'
