---
# Configure a net-new ESXi host
- hosts: 'esxi.tuxtech.com'
  connection: 'local'
  gather_facts: true
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars_files:
    - 'tuxtech-configuration.yml'
  module_defaults:
    # Would be nice if group/vmware worked correctly
    group/vmware:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    # Can this be external file for cleanliness?
    community.vmware.vmware_host_ntp:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_host_dns:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_host_datastore:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_host_ipv6:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_host_powermgmt_policy:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
  tasks:

    # This doesn't seem to work on a standalone ESXi host
    # - name: Add ESXi license and assign to the ESXi host
    #   community.vmware.vcenter_license:
    #     hostname: '{{ vmware_hostname }}'
    #     username: '{{ vmware_username }}'
    #     password: '{{ vmware_password }}'
    #     validate_certs: false
    #     #esxi_hostname: '{{ vmware_hostname }}'
    #     license: 'JV425-4h100-vzhh8-q23np-3a9pp'
    #     state: 'present'


    - name: 'Set NTP servers for an ESXi Host'
      community.vmware.vmware_host_ntp:
        esxi_hostname: '{{ vmware_hostname }}'
        ntp_servers:
          - '192.168.1.6'
        state: 'present'


    - name: 'Start ntpd setting for an ESXi Host'
      community.vmware.vmware_host_service_manager:
        esxi_hostname: '{{ vmware_hostname }}'
        service_name: 'ntpd'
        state: 'present'


    - name: 'Configure DNS for an ESXi host'
      community.vmware.vmware_host_dns:
        type: 'static'
        domain: 'tuxtech.com'
        dns_servers:
          - '192.168.1.6'
        search_domains:
          - 'tuxtech.com'


    - name: 'Disable IPv6 for a host system'
      community.vmware.vmware_host_ipv6:
        esxi_hostname: '{{ vmware_hostname }}'
        state: 'disabled'


    - name: 'Mount NFS v4.1 datastores to ESXi'
      community.vmware.vmware_host_datastore:
        datastore_name: '{{ item.name }}'
        datastore_type: '{{ item.type }}'
        nfs_server: '{{ item.server }}'
        nfs_path: '{{ item.path }}'
        nfs_ro: false
        esxi_hostname: '{{ inventory_hostname }}'
        state: 'present'
      loop:
        - {'name': 'nas412', 'server': 'nas412', 'path': '/volume1/vmfs1', 'type': 'nfs41'}


    - name: 'Set the Power Management Policy of a host system to high-performance'
      community.vmware.vmware_host_powermgmt_policy:
        esxi_hostname: '{{ vmware_hostname }}'
        policy: 'balanced'
