---
# Populate Linux hosts in to Foreman with correct host attributes, eg: MAC address
- hosts: all
  connection: local
  gather_facts: true
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars_files:
    - 'tuxtech-configuration.yml'
  module_defaults:
    # Can this be external file for cleanliness?
    community.vmware.vmware_vm_info:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest_boot_manager:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
  tasks:

    - name: 'Gather all registered virtual machines'
      community.vmware.vmware_vm_info:
      register: vminfo
      delegate_to: 'localhost'


    - name: 'debug'
      debug:
        # var: vminfo.virtual_machines
        var: ansible_date_time


    - name: 'Set BIOS Boot wait time to 4000ms'
      community.vmware.vmware_guest_boot_manager:
        name: '{{ inventory_hostname }}'
        boot_delay: 4000
        # Set boot mode to cd-rom for provision
      # delegate_to: 'localhost'


      # Register host in foreman


      # Set boot mode to disk for regular access
