---
# tasks file for 10_configure_foreman
- block:
  - name: 'Install required Foreman/Satellite packages'
    ansible.builtin.dnf:
      name:
        - 'rubygem-hammer_cli_foreman_bootdisk'     # Hammer CLI plug-in for bootdisk
        - 'grub2-efi-x64'
        - 'shim-x64'
      state: 'present'


  - name: 'Define subnet 192.168.1.0/24'
    theforeman.foreman.subnet:
      name: '192.168.1.0'
      network: '192.168.1.0'
      network_type: 'IPv4'
      mask: '255.255.255.0'
      gateway: '192.168.1.1'
      dns_primary: '192.168.1.6'
      dns_secondary: '192.168.1.1'
      boot_mode: 'Static'
      mtu: 1500
      ipam: 'None'
      domains:
        - 'tuxtech.com'
      remote_execution_proxies:
        - '{{ inventory_hostname }}'
      locations:
        - 'Default Location'
      organizations:
        - 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  # Define Partition Tables
  - name: 'Define partition table TuxTech'
    theforeman.foreman.partition_table:
      name: 'Kickstart default - TuxTech'
      os_family: 'Redhat'
      locations:
        - 'Default Location'
      organizations:
        - 'TuxTech'
      locked: false
      layout: |
        zerombr
        clearpart --all --initlabel
        # Physical layout
        partition /boot --ondisk=sda --size=1000  --grow --fstype=xfs --asprimary
        partition pv.21 --onpart=sdb --size=16384 --grow
        # LVM layout
        volgroup vg_root pv.21
        logvol /     --vgname=vg_root --name=lv_root --size=10240 --fstype=xfs
        logvol /home --vgname=vg_root --name=lv_home --size=2048  --fstype=xfs
        logvol swap  --vgname=vg_root --name=lv_swap --size=4096
      state: 'present'
    delegate_to: 'localhost'


  # Define Templates
  - name: 'Define template Kickstart default iPXE - TuxTech'
    theforeman.foreman.provisioning_template:
      name: 'Kickstart default iPXE - TuxTech'
      kind: 'iPXE'
      template: |-
        #!gpxe
        <%#
        kind: iPXE
        name: Kickstart default iPXE
        model: ProvisioningTemplate
        oses:
        - AlmaLinux
        - CentOS
        - Fedora
        - RedHat
        - Rocky
        %>
        <%
          pxe_kernel_options = @host.params['pxe_kernel_options'] 
          iface = @host.provision_interface
          subnet4 = iface.subnet
          subnet6 = iface.subnet6

          if subnet4 && !subnet4.dhcp_boot_mode?
            ks = foreman_url('provision', static: '1')
          elsif subnet6 && !subnet6.dhcp_boot_mode?
            ks = foreman_url('provision', static6: '1')
          else
            ks = foreman_url('provision')
          end
        -%>

        echo Trying to ping Gateway: ${netX/gateway}
        ping --count 1 ${netX/gateway} || echo Ping to Gateway failed or ping command not available.
        echo Trying to ping DNS: ${netX/dns}
        ping --count 1 ${netX/dns} || echo Ping to DNS failed or ping command not available.

        kernel <%= "#{@host.url_for_boot(:kernel)}" %> initrd=initrd.img ks=<%= ks %> <%= pxe_kernel_options %> <%= snippet("kickstart_kernel_options", variables: {ipxe_net: true}).strip %>
        initrd <%= "#{@host.url_for_boot(:initrd)}" %>
        imgstat
        sleep 2
        boot
      operatingsystems: 
        # - 'CentOS 7'
        # - 'CentOS_Stream 8'
      locations: 
        - 'Default Location'
      organizations: 
        - 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Define snippet template Kickstart default custom post'
    # This is a built-in default to include, if it exists
    theforeman.foreman.provisioning_template:
      name: 'Kickstart default custom post'
      kind: 'snippet'
      template: |-
        eject -v
      locations: 
        - 'Default Location'
      organizations: 
        - 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  # Define Operating Systems
  - name: 'Define operating system CentOS 7'
    theforeman.foreman.operatingsystem:
      name: 'CentOS'
      major: 7
      description: 'CentOS 7'
      os_family: 'Redhat'
      password_hash: 'SHA512'
      architectures:
        - 'x86_64'
      ptables:
        - 'Kickstart default'
        - 'Kickstart default - TuxTech'
      media:
        - 'CentOS 7 mirror'
      provisioning_templates:
        - 'Kickstart default iPXE - TuxTech'
        - 'Kickstart default'
        - 'Kickstart default finish'
        - 'Kickstart default user data'
        - 'Linux host_init_config default'
    delegate_to: 'localhost'


  - name: 'Define operating system CentOS Stream 8'
    theforeman.foreman.operatingsystem:
      name: 'CentOS_Stream'
      major: 8
      description: 'CentOS Stream 8'
      os_family: 'Redhat'
      password_hash: 'SHA512'
      architectures:
        - 'x86_64'
      ptables:
        - 'Kickstart default'
        - 'Kickstart default - TuxTech'
      media:
        - 'CentOS Stream'
      provisioning_templates:
        - 'Kickstart default iPXE - TuxTech'
        - 'Kickstart default'
        - 'Kickstart default finish'
        - 'Kickstart default user data'
        - 'Linux host_init_config default'
    delegate_to: 'localhost'


  - name: 'Define operating system provisioning template associations'
    theforeman.foreman.os_default_template:
      operatingsystem: '{{ item.os }}'
      provisioning_template: '{{ item.tmpl }}'
      template_kind: '{{ item.kind }}'
      state: 'present'
    loop:
      - { 'os': 'CentOS 7', 'tmpl': 'Kickstart default iPXE - TuxTech', 'kind': 'iPXE' }
      - { 'os': 'CentOS 7', 'tmpl': 'Kickstart default', 'kind': 'provision' }
      - { 'os': 'CentOS 7', 'tmpl': 'Kickstart default finish', 'kind': 'finish' }
      - { 'os': 'CentOS 7', 'tmpl': 'Kickstart default user data', 'kind': 'user_data' }
      - { 'os': 'CentOS Stream 8', 'tmpl': 'Kickstart default iPXE - TuxTech', 'kind': 'iPXE' }
      - { 'os': 'CentOS Stream 8', 'tmpl': 'Kickstart default', 'kind': 'provision' }
      - { 'os': 'CentOS Stream 8', 'tmpl': 'Kickstart default finish', 'kind': 'finish' }
      - { 'os': 'CentOS Stream 8', 'tmpl': 'Kickstart default user data', 'kind': 'user_data' }


  # Create provisioning hostgroups
  - name: 'Define hostgroup CentOS_7_GP'
    theforeman.foreman.hostgroup:
      name: 'CentOS_7_GP'
      description: 'CentOS 7 - General Purpose'
      # lifecycle_environment: 'Library'
      # content_view: 'Default Organization View'
      # content_source: '{{ inventory_hostname }}'
      environment: 'production'
      puppet_proxy: '{{ inventory_hostname }}'
      puppet_ca_proxy: '{{ inventory_hostname }}'
      domain: 'tuxtech.com'
      subnet: '192.168.1.0'
      architecture: 'x86_64'
      operatingsystem: 'CentOS 7'
      medium: 'CentOS 7 mirror'
      ptable: 'Kickstart default - TuxTech'
      pxe_loader: 'PXELinux BIOS'
      root_pass: '{{ foreman_password }}'
      parameters:
        - name: 'pxe_kernel_options'
          parameter_type: 'string'
          value: 'net.ifnames=0 biosdevname=0'
        - name: 'remote_execution_ssh_keys'
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa3aUqQU68g7DXPTPx3r7uLz1FGI+WYs062x3qmuICVT789Q\
                  E++tWDKRO/Yg3EZwyKzEjFkDeASg8V5QkhkwVKqEmm7UCOreeEPbSLyr+NWGCeHhS7o2ZTfgROjgsBPdwFmYCq\
                  tTXQMSHn431CwdpGEAwneANahOzEvFCgY947Ox83arYFexVd+BBLYaUK7Felwag3PlhKZfDmnydbOfGATbN9JL\
                  jEGZeD15DdyewgaH83kJU9tWU/k3cx1l9SbHVwDoZrdXxKzgQhmE5KshAms8kcdtDfTkTLOpLd8kkNc3dh4wFs\
                  XAOwNy5zjeHpTxkYJr5b1MRBj7OdpdMrVNyP len@lenmbpr15.tuxtech.com"
      locations: 
        - 'Default Location'
      organization: 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Define hostgroup CentOSStream_8_GP'
    theforeman.foreman.hostgroup:
      name: 'CentOSStream_8_GP'
      description: 'CentOS Stream 8 - General Purpose'
      # lifecycle_environment: 'Library'
      # content_view: 'Default Organization View'
      # content_source: '{{ inventory_hostname }}'
      environment: 'production'
      puppet_proxy: '{{ inventory_hostname }}'
      puppet_ca_proxy: '{{ inventory_hostname }}'
      domain: 'tuxtech.com'
      subnet: '192.168.1.0'
      architecture: 'x86_64'
      operatingsystem: 'CentOS Stream 8'
      medium: 'CentOS Stream'
      ptable: 'Kickstart default - TuxTech'
      pxe_loader: 'PXELinux BIOS'
      root_pass: '{{ foreman_password }}'
      parameters:
        - name: 'pxe_kernel_options'
          parameter_type: 'string'
          value: 'net.ifnames=0 biosdevname=0'
        - name: 'remote_execution_ssh_keys'
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa3aUqQU68g7DXPTPx3r7uLz1FGI+WYs062x3qmuICVT789Q\
                  E++tWDKRO/Yg3EZwyKzEjFkDeASg8V5QkhkwVKqEmm7UCOreeEPbSLyr+NWGCeHhS7o2ZTfgROjgsBPdwFmYCq\
                  tTXQMSHn431CwdpGEAwneANahOzEvFCgY947Ox83arYFexVd+BBLYaUK7Felwag3PlhKZfDmnydbOfGATbN9JL\
                  jEGZeD15DdyewgaH83kJU9tWU/k3cx1l9SbHVwDoZrdXxKzgQhmE5KshAms8kcdtDfTkTLOpLd8kkNc3dh4wFs\
                  XAOwNy5zjeHpTxkYJr5b1MRBj7OdpdMrVNyP len@lenmbpr15.tuxtech.com"
      locations: 
        - 'Default Location'
      organization: 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Define hostgroup CentOSStream_8_IDM'
    theforeman.foreman.hostgroup:
      name: 'CentOSStream_8_IDM'
      description: 'CentOS Stream 8 - Identity Management'
      # lifecycle_environment: 'Library'
      # content_view: 'Default Organization View'
      # content_source: '{{ inventory_hostname }}'
      environment: 'production'
      puppet_proxy: '{{ inventory_hostname }}'
      puppet_ca_proxy: '{{ inventory_hostname }}'
      domain: 'tuxtech.com'
      subnet: '192.168.1.0'
      architecture: 'x86_64'
      operatingsystem: 'CentOS Stream 8'
      medium: 'CentOS Stream'
      ptable: 'Kickstart default - TuxTech'
      pxe_loader: 'PXELinux BIOS'
      root_pass: '{{ foreman_password }}'
      parameters:
        - name: 'pxe_kernel_options'
          parameter_type: 'string'
          value: 'net.ifnames=0 biosdevname=0'
        - name: 'remote_execution_ssh_keys'
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa3aUqQU68g7DXPTPx3r7uLz1FGI+WYs062x3qmuICVT789Q\
                  E++tWDKRO/Yg3EZwyKzEjFkDeASg8V5QkhkwVKqEmm7UCOreeEPbSLyr+NWGCeHhS7o2ZTfgROjgsBPdwFmYCq\
                  tTXQMSHn431CwdpGEAwneANahOzEvFCgY947Ox83arYFexVd+BBLYaUK7Felwag3PlhKZfDmnydbOfGATbN9JL\
                  jEGZeD15DdyewgaH83kJU9tWU/k3cx1l9SbHVwDoZrdXxKzgQhmE5KshAms8kcdtDfTkTLOpLd8kkNc3dh4wFs\
                  XAOwNy5zjeHpTxkYJr5b1MRBj7OdpdMrVNyP len@lenmbpr15.tuxtech.com"
      locations: 
        - 'Default Location'
      organization: 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Define hostgroup CentOSStream_8_FMN'
    theforeman.foreman.hostgroup:
      name: 'CentOSStream_8_FMN'
      description: 'CentOS Stream 8 - Foreman/Satellite'
      # lifecycle_environment: 'Library'
      # content_view: 'Default Organization View'
      # content_source: '{{ inventory_hostname }}'
      environment: 'production'
      puppet_proxy: '{{ inventory_hostname }}'
      puppet_ca_proxy: '{{ inventory_hostname }}'
      domain: 'tuxtech.com'
      subnet: '192.168.1.0'
      architecture: 'x86_64'
      operatingsystem: 'CentOS Stream 8'
      medium: 'CentOS Stream'
      ptable: 'Kickstart default - TuxTech'
      pxe_loader: 'PXELinux BIOS'
      root_pass: '{{ foreman_password }}'
      parameters:
        - name: 'pxe_kernel_options'
          parameter_type: 'string'
          value: 'net.ifnames=0 biosdevname=0'
        - name: 'remote_execution_ssh_keys'
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa3aUqQU68g7DXPTPx3r7uLz1FGI+WYs062x3qmuICVT789Q\
                  E++tWDKRO/Yg3EZwyKzEjFkDeASg8V5QkhkwVKqEmm7UCOreeEPbSLyr+NWGCeHhS7o2ZTfgROjgsBPdwFmYCq\
                  tTXQMSHn431CwdpGEAwneANahOzEvFCgY947Ox83arYFexVd+BBLYaUK7Felwag3PlhKZfDmnydbOfGATbN9JL\
                  jEGZeD15DdyewgaH83kJU9tWU/k3cx1l9SbHVwDoZrdXxKzgQhmE5KshAms8kcdtDfTkTLOpLd8kkNc3dh4wFs\
                  XAOwNy5zjeHpTxkYJr5b1MRBj7OdpdMrVNyP len@lenmbpr15.tuxtech.com"
      locations: 
        - 'Default Location'
      organization: 'TuxTech'
      state: 'present'
    delegate_to: 'localhost'


  # Setup hammer credentials

  # Foreman bootdisk configuration
  - name: 'Ensure /var/lib/foreman/bootdisk exists'
    ansible.builtin.file:
      path: '/var/lib/foreman/bootdisk'
      owner: 'foreman'
      group: 'foreman'
      mode: '0755'
      state: 'directory'


  - name: 'Copy system boot firmware images to /var/lib/foreman/bootdisk'
    ansible.builtin.copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: 'foreman'
      group: 'foreman'
      mode: '0644'
      remote_src: true
    loop:
      - { 'src': '/boot/efi/EFI/centos/grubx64.efi', 'dest': '/var/lib/foreman/bootdisk/' }
      - { 'src': '/boot/efi/EFI/centos/shimx64.efi', 'dest': '/var/lib/foreman/bootdisk/' }


  - name: 'Generate foreman boot ISO'
  # https://github.com/theforeman/foreman_bootdisk
  # https://github.com/theforeman/hammer_cli_foreman_bootdisk
  #  foreman-rake bootdisk:generate:generic OUTPUT=/tmp/foreman.iso
    ansible.builtin.command:
      cmd: '/usr/sbin/foreman-rake bootdisk:generate:generic OUTPUT=/tmp/bootdisk_{{ inventory_hostname }}.iso'
      # cmd: '/usr/bin/hammer bootdisk generic'
    when:
      # Add more logical check - if file exists and older than 1 day?
      - true


  - name: 'Copy /tmp/bootdisk_{{ inventory_hostname }}.iso to ESXi datastore'
    community.vmware.vsphere_copy:
      src: '/tmp/bootdisk_{{ inventory_hostname }}.iso'
      datastore: 'nas412'
      path: '/ISO Images/Linux/bootdisk_{{ inventory_hostname }}.iso'

  module_defaults:
    # Can this be external file for cleanliness?
    community.vmware.vsphere_copy:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    theforeman.foreman.subnet:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.partition_table:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.operatingsystem:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.hostgroup:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.provisioning_template:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.setting:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    theforeman.foreman.os_default_template:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ inventory_hostname }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
