---
# tasks file for 99_delete_vmclients
- block:
    - name: 'Delete VMware Virtual Machine guest'
      community.vmware.vmware_guest:
        name: '{{ inventory_hostname }}'
        force: true
        state: 'absent'
      delegate_to: 'localhost'

  module_defaults:
    # Can this be external file for cleanliness?
    community.vmware.vmware_guest:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
