---
# tasks file for 20_create_vmclients
- block:
  - name: 'Gather facts for ansible date/time variables'
    ansible.builtin.setup:
    delegate_to: 'localhost'

  - name: 'Create VMware Virtual Machine guest'
    community.vmware.vmware_guest:
      name: '{{ inventory_hostname }}'
      annotation: 'TuxTech automated provisioning: {{ inventory_hostname }} {{ hostgroup }} {{ ansible_date_time.date }} {{ ansible_date_time.time }}'
      folder: '/ha-datacenter/vm'
      guest_id: 'centos7_64Guest'
      hardware:
        num_cpus: '{{ num_cpus | default(2) }}'
        num_cpu_cores_per_socket: 1
        memory_mb: '{{ memory_mb | default(2560) }}'
        scsi: 'paravirtual'
        boot_firmware: 'bios'
        version: 13
      datastore: 'nas412'
      disk:
        - size_gb: '{{ sda_gb | default(1) }}'
          type: 'thin'
        - size_gb: '{{ sdb_gb | default(20) }}'
          type: 'thin'
      cdrom:
        - controller_number: 0
          unit_number: 0
          type: 'iso'
          iso_path: '[nas412] /ISO Images/Linux/bootdisk_{{ foreman_hostname }}.iso'
          state: 'present'
      networks:
        - name: 'VM Network'
          device_type: 'vmxnet3'
          connected: true
          start_connected: true
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Set VM BIOS Boot wait time to 3000ms'
    community.vmware.vmware_guest_boot_manager:
      name: '{{ inventory_hostname }}'
      boot_delay: 3000
      boot_order:
        - 'floppy'
        - 'cdrom'
        - 'disk'
        - 'ethernet'
    delegate_to: 'localhost'


  - name: Toggle VM power (on) to generate a MAC
    community.vmware.vmware_guest_powerstate:
      name: '{{ inventory_hostname }}'
      state: 'powered-on'
    delegate_to: 'localhost'


  - name: Toggle VM power (off) to generate a MAC
    community.vmware.vmware_guest_powerstate:
      name: '{{ inventory_hostname }}'
      state: 'powered-off'
    delegate_to: 'localhost'

  module_defaults:
    # Can this be external file for cleanliness?
    community.vmware.vmware_guest:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest_boot_manager:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest_powerstate:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
