---
# tasks file for 99_delete_hostclients
- block:
  - name: 'Delete host clients in Foreman'
    theforeman.foreman.host:
      name: '{{ inventory_hostname }}'
      state: 'absent'
    delegate_to: 'localhost'

  module_defaults:
    # Can this be external file for cleanliness?
    theforeman.foreman.host:
      username: '{{ tuxtech.foreman.username }}'
      password: '{{ tuxtech.foreman.password }}'
      server_url: 'https://{{ tuxtech.foreman.hostname  }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
