---
# tasks file for 10_configure_esxi
- block:
  - name: 'Set NTP servers for ESXi Host'
    community.vmware.vmware_host_ntp:
      esxi_hostname: '{{ inventory_hostname }}'
      ntp_servers:
        - '192.168.1.6'
      state: 'present'
    delegate_to: 'localhost'


  - name: 'Start ntpd and ssh services for ESXi Host'
    community.vmware.vmware_host_service_manager:
      esxi_hostname: '{{ inventory_hostname }}'
      service_name: '{{ item }}'
      service_policy: 'on'
      state: 'present'
    loop:
      - 'ntpd'
      - 'TSM'
      - 'TSM-SSH'
    delegate_to: 'localhost'


  - name: 'Configure DNS for ESXi host'
    community.vmware.vmware_host_dns:
      type: 'static'
      domain: 'tuxtech.com'
      dns_servers:
        - '192.168.1.6'
      search_domains:
        - 'tuxtech.com'
    delegate_to: 'localhost'


  - name: 'Disable IPv6 for ESXi host'
    community.vmware.vmware_host_ipv6:
      esxi_hostname: '{{ inventory_hostname }}'
      state: 'disabled'
    delegate_to: 'localhost'
    # TODO: Trigger a reboot if this changes


  - name: 'Mount NFS v4.1 datastores to ESXi host'
    community.vmware.vmware_host_datastore:
      datastore_name: '{{ item.name }}'
      datastore_type: '{{ item.type }}'
      nfs_server: '{{ item.server }}'
      nfs_path: '{{ item.path }}'
      nfs_ro: false
      esxi_hostname: '{{ inventory_hostname }}'
      state: 'present'
    loop:
      - {'name': 'nas412', 'server': 'nas412', 'path': '/volume1/vmfs1', 'type': 'nfs41'}
    delegate_to: 'localhost'


  - name: 'Set the Power Management Policy to balanced'
    community.vmware.vmware_host_powermgmt_policy:
      esxi_hostname: '{{ inventory_hostname }}'
      policy: 'balanced'
    delegate_to: 'localhost'

  module_defaults:
    # Would be nice if group/vmware worked correctly
    group/vmware:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    # Can this be external file for cleanliness?
    community.vmware.vmware_host_ntp:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    community.vmware.vmware_host_service_manager:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    community.vmware.vmware_host_dns:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    community.vmware.vmware_host_datastore:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    community.vmware.vmware_host_ipv6:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    community.vmware.vmware_host_powermgmt_policy:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
