---
# handlers file for 10_configure_esxi
- block:
  - name: 'restart ESXi'
    community.vmware.vmware_host_powerstate:
      esxi_hostname: '{{ inventory_hostname }}'
      force: true
      state: reboot-host
    delegate_to: localhost

  module_defaults:
    community.vmware.vmware_host_powerstate:
      hostname: '{{ inventory_hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
