---
# tasks file for 20_create_hostclients
- block:
  # Lookup MAC for virtual machine guest
  - name: 'Lookup virtual machine guest MAC address'
    community.vmware.vmware_guest_info:
      name: '{{ inventory_hostname }}'
      datacenter: 'ha-datacenter'
    register: vmguest_info
    delegate_to: 'localhost'


  - name: 'Register host to Foreman'
    theforeman.foreman.host:
      name: '{{ inventory_hostname }}'
      hostgroup: '{{ hostgroup }}'
      interfaces_attributes:
        - type: 'interface'
          identifier: 'eth0'
          mac: '{{ vmguest_info.instance.hw_eth0.macaddress }}'
          ip: '{{ ipaddr }}'
          primary: true
          provision: true
      build: true
      organization: 'TuxTech'
      location: 'Default Location'
      state: 'present'
    delegate_to: 'localhost'

  module_defaults:
    # Can this be external file for cleanliness?
    theforeman.foreman.host:
      username: '{{ tuxtech.foreman.username }}'
      password: '{{ tuxtech.foreman.password }}'
      server_url: 'https://{{ tuxtech.foreman.hostname }}'
      validate_certs: false
    community.vmware.vmware_guest_info:
      hostname: '{{ tuxtech.vmware.hostname }}'
      username: '{{ tuxtech.vmware.username }}'
      password: '{{ tuxtech.vmware.password }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
