---
# Configuration for CentOSStream_8_FMN hostgroups
- block:
  - name: 'Configure EL/CentOS 8 Base OS'
    include_tasks: 'el8_postprovision.yml'

  # Configure additional "Foreman/Satellite" requirements
  - name: 'Remove default puppet package as Foreman installs its own'
    ansible.builtin.dnf:
      name:
        - 'puppet'
      autoremove: true
      state: 'absent'


  - name: 'Remove stale puppet ssl certificates from provisioning'
    ansible.builtin.file:
      name: '/etc/puppetlabs/puppet/ssl/'
      state: 'absent'


  - name: 'Reboot'
    ansible.builtin.reboot:
