---
# Configuration for CentOSStream_8_GP hostgroups
- block:
  - name: 'Configure EL/CentOS 8 Base OS'
    include_tasks: 'el8_postprovision.yml'

  # Configure additional "General Purpose" requirements
  - name: 'Reboot'
    ansible.builtin.reboot:
