---
# Configuration for CentOS_7_GP host groups
- block:
  - name: 'Configure EL/CentOS 7 Base OS'
    import_tasks: 'tuxtech-os-el7_postprovision.yml'

  # Configure additional "General Purpose" requirements
  - name: 'Reboot'
    ansible.builtin.reboot:
