---
# Configuration for CentOS_7_GP host groups
- block:
  - name: 'Configure Enterprise Linux/CentOS 7 Base OS'
    import_tasks: 'tuxtech-os-el7_postprovision.yml'

  # Configure additional "General Purpose" requirements
  - name: 'Reboot'
    ansible.builtin.reboot:


# handlers:
#   - name: 'rebuild grub'
#     ansible.builtin.command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'

#   - name: 'restart postfix'
#     ansible.builtin.service:
#       name: 'postfix'
#       state: 'restarted'
