---
- block:
  - name: '[ansible.builtin.dnf] Install module stream idm:client'
    ansible.builtin.dnf:
      name:
        - '@idm:client'


  - name: '[ansible.builtin.command] ipa-client-install to join IDM Domain idm.tuxtech.com'
    ansible.builtin.command:
      argv:
        - /usr/sbin/ipa-client-install
        - --domain=idm.tuxtech.com
        - --realm=IDM.TUXTECH.COM
        - --principal={{ tuxtech.idm.username }}
        - --password={{ tuxtech.idm.password }}
        - --mkhomedir
        - --force-join
        - --unattended
    ignore_errors: true
    no_log: true
  when:
    - hostgroup != 'CentOSStream_8_FMN'
    - hostgroup != 'CentOSStream_8_IDM'
