---
# tasks file for 10_provision_os
- block:
  - name: Power on vm to start OS provisioning
    community.vmware.vmware_guest_powerstate:
      name: '{{ inventory_hostname }}'
      state: 'powered-on'
    delegate_to: 'localhost'


  - name: 'Wait for operating system to be installed'
    wait_for:
      host: '{{ inventory_hostname }}'
      port: 22
      search_regex: 'OpenSSH'
      delay: 15
      sleep: 15
      timeout: 3600
    delegate_to: 'localhost'


  - name: 'Remove Foreman boot CD-ROM'
    community.vmware.vmware_guest:
      name: '{{ inventory_hostname }}'
      cdrom:
        type: 'none'
    delegate_to: 'localhost'


  - name: 'Configure hostgroup/os settings'
    include_tasks: '{{ hostgroup }}.yml'


  module_defaults:
    # Can this be external file for cleanliness?
    community.vmware.vmware_guest_powerstate:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    community.vmware.vmware_guest:
      hostname: '{{ vmware_hostname }}'
      username: '{{ vmware_username }}'
      password: '{{ vmware_password }}'
      validate_certs: false
    theforeman.foreman.host:
      username: '{{ foreman_username }}'
      password: '{{ foreman_password }}'
      server_url: 'https://{{ foreman_hostname }}'
      validate_certs: false
    blockinfile:
      marker: '# {mark} TUXTECH ANSIBLE MANAGED BLOCK'
